### ISSUE TITLE
Update npm package install to utilize package.json config

### ISSUE THREAD

**Issue by karrots** [cacack/ansible-moteino-gateway#3]
The Moteino gateway repository now has a package.json file specifying dependencies and their versions. To be more dynamic the `Install required Node.JS packages` task can be converted to just `npm install` run from the repository root.

**Comment by cacack** [comment]
I debated heading that route but opted to define them myself so that the Ansible playbook would be idempotent.  If I run `npm install` from the shell, then I need to figure out a way to only trigger it when the node packages need installed or updated.

But after just checking the [npm module docs](http://docs.ansible.com/ansible/npm_module.html), just specifying the path argument is sufficient for Ansible to read the package.json file....

**Comment by cacack** [comment]
I want to run the playbook on a fresh install, but I don't anticipate any problems.

**Comment by cacack** [comment]
Just ran through a fresh install without problems.  Ansible did use the package.json file so I'm closing this issues as fixed.
